import type { AppTheme, ThemeKey } from './types';

export const DEFAULT_THEME_KEY: ThemeKey = 'healing-blue';

export const themePresets: AppTheme[] = [
  {
    key: 'klein-blue',
    name: '克莱因蓝',
    primary: '#002FA7',
    accent: '#FEF46D',
    background: '#F5F7FF',
    surface: '#FFFFFF',
    surfaceAlt: '#EAF0FF',
    text: '#071226',
    textMuted: '#69738A',
    textOnPrimary: '#FFFFFF',
    border: '#DCE5F7',
    success: '#28A06B',
    warning: '#B97800',
    danger: '#D24A43',
  },
  {
    key: 'healing-blue',
    name: '治愈蓝',
    primary: '#0081FF',
    accent: '#FEF99D',
    background: '#F8F7F2',
    surface: '#FFFFFF',
    surfaceAlt: '#EAF5FF',
    text: '#0B1224',
    textMuted: '#697287',
    textOnPrimary: '#FFFFFF',
    border: '#E2E8F2',
    success: '#28A06B',
    warning: '#B97800',
    danger: '#D24A43',
  },
  {
    key: 'honey-yellow',
    name: '蜂蜜黄',
    primary: '#FFE677',
    accent: '#FF6067',
    background: '#FFF9E7',
    surface: '#FFFFFF',
    surfaceAlt: '#FFF1BE',
    text: '#211A0A',
    textMuted: '#766C55',
    textOnPrimary: '#211A0A',
    border: '#EFE2B8',
    success: '#278D63',
    warning: '#9C6A00',
    danger: '#D24A43',
  },
  {
    key: 'mars-green',
    name: '马尔斯绿',
    primary: '#01847F',
    accent: '#FFAAA3',
    background: '#F2FAF8',
    surface: '#FFFFFF',
    surfaceAlt: '#E5F4F2',
    text: '#092322',
    textMuted: '#687B7A',
    textOnPrimary: '#FFFFFF',
    border: '#D6E9E7',
    success: '#258B61',
    warning: '#A36C00',
    danger: '#C94D50',
  },
  {
    key: 'neon-green',
    name: '荧光绿',
    primary: '#00FD00',
    accent: '#0947FE',
    background: '#F5FFF2',
    surface: '#FFFFFF',
    surfaceAlt: '#E8FFE5',
    text: '#061506',
    textMuted: '#5F755F',
    textOnPrimary: '#061506',
    border: '#D5F0D0',
    success: '#1E8B52',
    warning: '#916D00',
    danger: '#D04444',
  },
  {
    key: 'gentle-pink',
    name: '温柔粉',
    primary: '#FFDBDD',
    accent: '#652C97',
    background: '#FFF7F8',
    surface: '#FFFFFF',
    surfaceAlt: '#FFECEE',
    text: '#24101A',
    textMuted: '#806C74',
    textOnPrimary: '#24101A',
    border: '#F0DADF',
    success: '#288A64',
    warning: '#9B6800',
    danger: '#C5455D',
  },
  {
    key: 'tiffany-blue',
    name: '蒂芙尼蓝',
    primary: '#31D8CF',
    accent: '#57AA66',
    background: '#F2FBFA',
    surface: '#FFFFFF',
    surfaceAlt: '#E2F8F6',
    text: '#082625',
    textMuted: '#607B79',
    textOnPrimary: '#082625',
    border: '#D4ECEA',
    success: '#288B60',
    warning: '#9A6C00',
    danger: '#CB4A50',
  },
  {
    key: 'hermes-orange',
    name: '爱马仕橙',
    primary: '#FF7400',
    accent: '#2B3C3D',
    background: '#FFF7EF',
    surface: '#FFFFFF',
    surfaceAlt: '#FFEAD8',
    text: '#241100',
    textMuted: '#806A5A',
    textOnPrimary: '#FFFFFF',
    border: '#F0D9C6',
    success: '#26885F',
    warning: '#A15F00',
    danger: '#C94B43',
  },
  {
    key: 'burgundy-red',
    name: '勃艮第红',
    primary: '#990033',
    accent: '#DDCDB7',
    background: '#FBF6F7',
    surface: '#FFFFFF',
    surfaceAlt: '#F4E9EB',
    text: '#260611',
    textMuted: '#7A6670',
    textOnPrimary: '#FFFFFF',
    border: '#E8D8DD',
    success: '#2B8B61',
    warning: '#A06A00',
    danger: '#C83E55',
  },
];

export const themeByKey = themePresets.reduce(
  (themes, theme) => ({ ...themes, [theme.key]: theme }),
  {} as Record<ThemeKey, AppTheme>,
);

export function isThemeKey(value: unknown): value is ThemeKey {
  return typeof value === 'string' && value in themeByKey;
}

export function getThemeByKey(themeKey?: string): AppTheme {
  return isThemeKey(themeKey) ? themeByKey[themeKey] : themeByKey[DEFAULT_THEME_KEY];
}
